### ISSUE TITLE
Report with variable name

### ISSUE THREAD

**Issue by sanposhiho** [sanposhiho/wastedassign#22]
want to display the variables that were the subject of the report.

**Comment by timbunce** [comment]
As an example, ineffassign does report the variable name and that allows certain cases to be ignored:
```yaml
  exclude-rules:
    - linters:
      - ineffassign
      text: "ineffectual assignment to ctx" # often span,ctx := StartSpan where ctx isn't _currently_ used
```
